### ISSUE TITLE
Function mcrypt_get_iv_size() is deprecated

### ISSUE THREAD

**Issue by parab-aditya** [NowSquare/Mobile-Platform#1]
Deploying on a PHP 7.1 (Serverpilot) gives this error:
 `Function mcrypt_get_iv_size() is deprecated`

**Probable cause:**
The script is using `MCRYPT_RIJNDAEL_128` and it doesn't seem to work well with PHP 7.1 

**Possible solution:**
Update to Laravel 5 to work well with PHP 7.1
Else install the [legacy encrypter](https://github.com/laravel/legacy-encrypter) and use it to update all  encrypted data to use the `AES-256-CBC` cipher which has been the default cipher since Laravel 5.1

**Current Hotfix**
`error_reporting(E_ALL ^ E_DEPRECATED);` in app.php

**Comment by sem-nowsquare** [comment]
Thanks, upgrading to L5 is no option due to third party libs that have to be replaced and re-implemented. Feel free to do a pull request :) For now I've applied the hotfix.
